// Generated by https://quicktype.io

import { Hero } from './Hero';

export interface HeroesRes {
    code:            number;
    status:          string;
    copyright:       string;
    attributionText: string;
    attributionHTML: string;
    etag:            string;
    data:            HeroesList;
}

export interface HeroesList {
    offset:  number;
    limit:   number;
    total:   number;
    count:   number;
    results: Hero[];
}

